title: Primera página en GitHub Pages
author: Luis Polina
email: luis.2820001@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Comenzamos creando este sitio para aprender a utilizar
  GitHub Pages. Hasta el momento no se encontraron complicaciones.
  ¡Sigamos aprendiendo!

# social links
twitter_username: RP_Luis28 # DO NOT include the @ character, or else the build will fail!
github_username:  L7PR # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
