title: Primera página de GitHub Pages
author: P4R
email: luis.282001@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Empezamos creando esta página con el fin aprender a utilizar
  GitHub Pages. Hasta ahora el manejo de herramientas no
  tiene complicaciones

# social links
twitter_username: RP_Luis28 # DO NOT include the @ character, or else the build will fail!
github_username:  L7PR # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
